/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author acer
 */
import view.formBarang;
import javax.swing.JOptionPane;
import view.formLaporanPenjualan;
import view.formNota;
import view.formPelanggan;
import view.formPesanan;


public class menuUtama extends javax.swing.JFrame {

    /**
     * Creates new form menuUtama
     */
    public menuUtama() {
        super("Sistem Informasi Penjualan Tunai");
        setLocation(100,100);
        initComponents();
        setContentPane(dskPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMaster = new javax.swing.JMenu();
        formBarang = new javax.swing.JMenuItem();
        formPelanggan = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        formExit = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        formPesanan = new javax.swing.JMenuItem();
        formNota = new javax.swing.JMenuItem();
        mnLaporan = new javax.swing.JMenu();
        formCetakLaporan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPaneLayout = new javax.swing.GroupLayout(dskPane);
        dskPane.setLayout(dskPaneLayout);
        dskPaneLayout.setHorizontalGroup(
            dskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        dskPaneLayout.setVerticalGroup(
            dskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mnMaster.setText("Master");

        formBarang.setText("Entry Data Barang");
        formBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formBarangActionPerformed(evt);
            }
        });
        mnMaster.add(formBarang);

        formPelanggan.setText("Entry Data Pelanggan");
        formPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPelangganActionPerformed(evt);
            }
        });
        mnMaster.add(formPelanggan);
        mnMaster.add(separator);

        formExit.setText("Keluar");
        formExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formExitActionPerformed(evt);
            }
        });
        mnMaster.add(formExit);

        jMenuBar1.add(mnMaster);

        mnTransaksi.setText("Transaksi");

        formPesanan.setText("Entry Pesanan");
        formPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPesananActionPerformed(evt);
            }
        });
        mnTransaksi.add(formPesanan);

        formNota.setText("Cetak Nota");
        formNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formNotaActionPerformed(evt);
            }
        });
        mnTransaksi.add(formNota);

        jMenuBar1.add(mnTransaksi);

        mnLaporan.setText("Laporan");

        formCetakLaporan.setText("Cetak Laporan Penjualan");
        formCetakLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formCetakLaporanActionPerformed(evt);
            }
        });
        mnLaporan.add(formCetakLaporan);

        jMenuBar1.add(mnLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dskPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 745, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dskPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 327, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formExitActionPerformed
        // TODO add your handling code here:
        int keluar = JOptionPane.showConfirmDialog(null, "Yakin keluar?", "KELUAR",JOptionPane.YES_NO_OPTION);
        if(keluar == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formExitActionPerformed

    private void formCetakLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formCetakLaporanActionPerformed
        // TODO add your handling code here:
        formLaporanPenjualan lp = new formLaporanPenjualan();
        dskPane.add(lp);
        lp.setVisible(true);
    }//GEN-LAST:event_formCetakLaporanActionPerformed

    private void formBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formBarangActionPerformed
        // TODO add your handling code here:
        formBarang brg = new formBarang();
        dskPane.add(brg);
        brg.setVisible(true);
    }//GEN-LAST:event_formBarangActionPerformed

    private void formPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPelangganActionPerformed
        // TODO add your handling code here:
        formPelanggan formPelanggan = new formPelanggan();
        dskPane.add(formPelanggan);
        formPelanggan.setVisible(true);
    }//GEN-LAST:event_formPelangganActionPerformed

    private void formPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPesananActionPerformed
        // TODO add your handling code here:
        formPesanan pesanan = new formPesanan();
        dskPane.add(pesanan);
        pesanan.setVisible(true);
    }//GEN-LAST:event_formPesananActionPerformed

    private void formNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formNotaActionPerformed
        // TODO add your handling code here:
        formNota nt = new formNota();
        dskPane.add(nt);
        nt.setVisible(true);
    }//GEN-LAST:event_formNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPane;
    private javax.swing.JMenuItem formBarang;
    private javax.swing.JMenuItem formCetakLaporan;
    private javax.swing.JMenuItem formExit;
    private javax.swing.JMenuItem formNota;
    private javax.swing.JMenuItem formPelanggan;
    private javax.swing.JMenuItem formPesanan;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenu mnMaster;
    private javax.swing.JMenu mnTransaksi;
    private javax.swing.JPopupMenu.Separator separator;
    // End of variables declaration//GEN-END:variables
}
